version: '3.9'
services:
  chatpot_web:
    container_name: 'chatpot_web'
    build:
        context: './..'
        dockerfile: './docker/php/Dockerfile'
  chatpot_db:
    container_name: 'chatpot_db'
    build:
      context: './..'
      dockerfile: './docker/mysql/Dockerfile'
    volumes:
      - dbData:/var/lib/mysql
volumes:
  dbData:
