-- Création de la base de données
CREATE DATABASE IF NOT EXISTS chatpot;

-- Création des tables
CREATE TABLE IF NOT EXISTS chatpot.rooms (
  id INT NOT NULL AUTO_INCREMENT,
  name VARCHAR(30) NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT UC_name UNIQUE (name)
)ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS chatpot.chat (
  id INT NOT NULL AUTO_INCREMENT,
  date_envoi DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  auteur VARCHAR(30) NOT NULL,
  contenu VARCHAR(255) NOT NULL,
  room_id INT NOT NULL,
  FOREIGN KEY (room_id) REFERENCES chatpot.rooms(id),
  PRIMARY KEY (id)
)ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS chatpot.users (
  id INT NOT NULL AUTO_INCREMENT,
  username VARCHAR(30) NOT NULL,
  password VARCHAR(255) NOT NULL,
  last_connection DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  last_alive DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT UC_username UNIQUE (username)
)ENGINE = InnoDB;